name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # このリポジトリのデータを読み込む
      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      
      - name: Run poetry install
        run: 
          poetry install
          poetry --version
      
      - name: Run tests
        run: poetry run python -m pytest 